### ISSUE TITLE
Conduct an audit of Hub's /people section for design opportunities for tbds

### ISSUE THREAD

**Issue by vendelal** [thoughtbot/design-system#139]
An audit of the information presented in the individual `/people` pages is a way to start looking at opportunities for creating more consistent layouts within Hub.

There is a lot of information across many tabs, with many actions associated with them. We're looking to see what all the versions are to find where we can consolidate into one (or a few) patterns.

This audit will be documented in [this figma file](https://www.figma.com/file/XPQRTsCdKXp9WhXFcgvlMl/Hub-Design-Audit).

**Comment by tysongach** [comment]
Hub just went through a big “redesign” so this no longer seems accurate and/or high-priority.
