### ISSUE TITLE
Incorrect button padding in Safari

### ISSUE THREAD

**Issue by cpjmcquillan** [thoughtbot/design-system#192]
## What it looks like
<img width="128" alt="Screenshot 2021-07-30 at 12 49 39" src="https://user-images.githubusercontent.com/25187547/127648882-383adcac-b762-4750-b903-770562c2bf22.png">

## What it should look like
<img width="170" alt="image" src="https://user-images.githubusercontent.com/25187547/127648936-86db2c97-3468-49fe-976a-1a4ba5f40117.png">

## Browsers tested
- Safari 14.1.2

## Additional context
We specify a `padding-inline` rule for supported browsers. 
https://github.com/thoughtbot/design-system/blob/0962eb42a9f76ecc856d5d5e2092ceb095fe6a86/src/button/lib/button.scss#L39

The variable we use `--tbds-button-padding-inline` is _supposedly_ resolved correctly by the browser: the variable inspector in developer tools shows the correct value. 

<img width="299" alt="image" src="https://user-images.githubusercontent.com/25187547/127649784-fa382c44-7da2-4e9b-bece-8cf1abda5498.png">

But the rule is not applied with the correct value.

If the variable is replaced with `1.5rem` in developer tools, the rule is applied correctly.

## What next
- Determine whether this is a safari bug, or a bug in the design system
- If the bug cannot be fixed, consider using a SASS variable instead to see if that resolves the issue

**Comment by LkeMitchll** [comment]
@cpjmcquillan I'm going to close this as constable.io is now gone. If we see an example of this bug again I'll re-open.
