### ISSUE TITLE
Add a CODEOWNERS to this repository

### ISSUE THREAD

**Issue by smaboshe** [thoughtbot/design-system#258]
I would like to add a CODEOWNERS file to this repository. Who would be good to have in the file? Who would like to volunteer to be added?

**Comment by smaboshe** [comment]
The CODEOWNERS will come in handy when we need to create new releases.

As the latest two people to create a release, @setphen and @LkeMitchll, would this be interesting to you?

**Comment by LkeMitchll** [comment]
I'm interested, Stephen no longer works at thoughtbot, so may not be interested.

**Comment by smaboshe** [comment]
Thank you, @LkeMitchll. We'll start the CODEOWNERS with you and can add to it over time.
