### ISSUE TITLE
Release a new version of `design-system`

### ISSUE THREAD

**Issue by smaboshe** [thoughtbot/design-system#266]
We have made several changes to `main` since [0.7.2](https://github.com/thoughtbot/design-system/commit/2681943e53e86d39befc2a092221609997199232). This issue is to have a discussion around bundling the latest changes into a new release of `design-system`. Tentatively, this would be version `0.7.3`, however, introducing [sass-collective/strip-unit](https://github.com/sass-collective/sass-collective/tree/master/packages/strip-unit) may require us to change the version in a more meaningful way since we are using [semver](https://semver.org/). Testing with existing projects will help us make decisions about all of this.

**Comment by mo-amama** [comment]
This issue has been resolved.
