### ISSUE TITLE
Does design-system `main` work with thoughtbot search?

### ISSUE THREAD

**Issue by smaboshe** [thoughtbot/design-system#274]
The [current README](https://github.com/thoughtbot/design-system#applications-using-tbds) states that `design-system` works with thoughtbot search. This issue is to run tests to make sure that this is the case. If `design-system` is indeed a dependency, please test that `design-system` `main` works as expected. If it is no longer a dependency, please update the README accordingly.

**Comment by mo-amama** [comment]
Yes, it does.
