### ISSUE TITLE
Does design-system `main` work with tbot?

### ISSUE THREAD

**Issue by smaboshe** [thoughtbot/design-system#277]
The [current README](https://github.com/thoughtbot/design-system#applications-using-tbds) states that `design-system` works with tbot. This issue is to run tests to make sure that this is the case. If `design-system` is indeed a dependency, please test that `design-system` `main` works as expected. If it is no longer a dependency, please update the README accordingly.

**Comment by mo-amama** [comment]
The tbot link on the read me file was pointing to thoughtbot.com, thoughtbot.com is already on the list of platforms using tbds, I have removed tbot from the list.
