### ISSUE TITLE
Responsive variants for utility classes

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/design-system#40]
e.g. `tbds-margin-top-2@medium`, `u-hidden@print`

**Comment by setphen** [comment]
Have you had success with this pattern before? I've frequently heard that media queries are a big weakness of single-rule classes.

**Comment by tysongach** [comment]
Yes, I’ve had a lot of success with them, but the underpinning is that we’re generally not building entire components using utility classes.

**Comment by tysongach** [comment]
Done via https://github.com/thoughtbot/design-system/pull/105
