### ISSUE TITLE
Add CodePen prototypes to each component

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/design-system#77]
We added a [CodePen prototype](https://codepen.io/thoughtbot/pen/Lvmamx) to the avatar component to showcase the real rendered version of the component. We should do the same for the rest of the components.

- [x] [Stack](https://github.com/thoughtbot/design-system/tree/master/src/stack)
- [x] [Button](https://github.com/thoughtbot/design-system/tree/master/src/button)
- [x] [Forms](https://github.com/thoughtbot/design-system/tree/master/src/forms)
- [x] [Media](https://github.com/thoughtbot/design-system/tree/master/src/media)
- [x] [App frame](https://github.com/thoughtbot/design-system/tree/master/src/app-frame)

**Comment by smharley** [comment]
Marking Media as complete:

https://github.com/thoughtbot/design-system/tree/master/src/media
https://codepen.io/thoughtbot/pen/LoNMxz

**Comment by smharley** [comment]
Adding App Frame Codepen here: #140
