### ISSUE TITLE
Pagination component

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/design-system#81]
## Current situation

- [On Hub](https://hub.thoughtbot.com/projects):

    <img width="222" alt="Screen Shot 2019-04-20 at 12 59 52" src="https://user-images.githubusercontent.com/903327/56460157-364acb80-636c-11e9-8811-b29db8da1b90.png"><br><img width="378" alt="Screen Shot 2019-09-16 at 21 04 50" src="https://user-images.githubusercontent.com/903327/65003251-b0ed2800-d8c5-11e9-8248-1ae6d6b3997a.png">

- [On Constable](https://constable.io/announcements?all=false&page=2):

    <img width="342" alt="Screen Shot 2019-09-16 at 21 04 21" src="https://user-images.githubusercontent.com/903327/65003245-aaf74700-d8c5-11e9-9728-b1900467ed20.png">

## Accessibility considerations

- Do not use color alone to indicate the current page
- On the markup side, encourage use of [`aria-current`](https://tink.uk/using-the-aria-current-attribute/), if possible
- Have reasonable tap targets

**Comment by setphen** [comment]
@tysongach what if the framework in use doesn't provide a way to add classes to the generated pagination links, or it generates different markup than expected?

**Comment by tysongach** [comment]
@setphen That’s a good question and something to consider. However, it would also be good to talk specifics, rather than what ifs. As a system, we should expect that each consumer is a unique situation and, where possible, we should provide a level of flexibility that works for those who have hard constraints.

In Rails I think we tend to use the [Kaminari gem](https://github.com/kaminari/kaminari), which does seem to offer a lot of flexibility.

**Comment by ericwbailey** [comment]
@tysongach I have the beginning of some [work on this component here](https://codepen.io/thoughtbot/pen/Rwbqpqd). A couple of steering questions for you:

1. What did you envision for smaller breakpoints? I've seen patterns where it collapses into a `select` element with next and previous page links. We could also just present it as a long list, like what is currently in the CodePen.
1. How configurable should the first pass be? From our past discussions, I'm assuming less is more, so pick one visual treatment and go with it, and leave things like border, fill toggles, and next/previous arrow icons for later?
