### ISSUE TITLE
Fix button icon alignment

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/design-system#95]
Icons inside buttons (`tbds-button__icon`) are not vertically aligned:

![Screen Shot 2019-05-31 at 15 41 35](https://user-images.githubusercontent.com/903327/58730617-a2ccd780-83ba-11e9-8b06-532ad141b196.png)

Using `inline-flex` and `align-items: center;` could be a good way to go.

**Comment by jadajc47** [comment]
#tbds-button__icon {
display: inline-flex;
align-items: center;
}

**Comment by Taylor-McNeil** [comment]
Tramainep & Taylor-McNeil are going to solve this
